language: python

jobs:
  include:
    - stage: "Static Analysis"
      name: "pylint"
      install:
        - pip install -r requirements.txt
        - pip install pylint
      script:
        - pylint mxmc --exit-zero

    - name: "flake8"
      install:
        - pip install flake8
      script:
        - flake8 mxmc/

    - stage: "Test"
      name: "tests"
      install:
        - pip install pytest pytest-cov pytest-mock docker docker-compose
        - pip install coveralls
        - pip install -r requirements.txt
      before_script:
        - export PYTHONPATH=$PYTHONPATH:$PWD
      script:
        - pytest --cov=mxmc --cov-report=term-missing tests/
      after_script:
        - coveralls
    - if: branch = main
        tests/deployment/run.py
